version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: IoT_grafana
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3001:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  prometheus:
    image: prom/prometheus:latest
    container_name: IoT_prometheus
    links:
      - alertmanager:alertmanager
    volumes:
      - ./prometheus/rules/:/etc/rules/
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090

  alertmanager:
    image: prom/alertmanager:latest
    container_name: IoT_alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9094:9093


