global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
- /etc/rules/*.yml

scrape_configs:
  
  - job_name: 'House Monitoring'
    static_configs:
      - targets:
        - 192.168.1.106