{
 "title": "BME280 - Temperature, Humidity and Barometric Pressure",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "comodo",
    "label": "comodo",
    "query": "label_values(bm280_temperature, comodo)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature $comodo",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "bm280_temperature{comodo='$comodo'}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "bm280_temperature{comodo='$comodo'}",
     "legendFormat": "{{comodo}}"
    }
   ]
  },
  {
   "title": "Humidity $comodo",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bm280_humidity{comodo='$comodo'}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bm280_humidity{comodo='$comodo'}",
     "legendFormat": "{{comodo}}"
    }
   ]
  },
  {
   "title": "Barometric Pressure $comodo",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "expr": "bm280_pressure{comodo='$comodo'}"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "bm280_pressure{comodo='$comodo'}",
     "legendFormat": "{{comodo}}"
    }
   ]
  }
 ]
}